# Generated by Django 3.2.3 on 2021-06-11 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
