# Generated by Django 3.2.3 on 2021-06-18 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProd',
            new_name='Categoria',
        ),
        migrations.RenameModel(
            old_name='ProdTienda',
            new_name='Producto',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
    ]
