# Generated by Django 3.2.3 on 2021-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_alter_producto_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
