# Generated by Django 3.2.3 on 2021-06-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_alter_producto_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
    ]
