# Generated by Django 3.2.3 on 2021-06-23 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_auto_20210623_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='key',
        ),
    ]
