# Generated by Django 3.2.3 on 2021-06-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0010_auto_20210623_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
